<div class="input-form disable-display">
	<div class="row">
		<div class="col-md-3 left-option">
			<h3 class="left-btn">CF</h3>
		</div>
		<div class="col-md-1 middle-option">
			<input type="checkbox" name="switch" id="switch">
		</div>
		<div class="col-md-3 right-option">
			<h3 class="right-btn">SELF</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<h4>Content</h4>
		</div>
		<div class="col-md-9">
			<textarea name='diary-content' id='diary-content' ></textarea>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-5">
			<h3 id="upload">Upload</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-5 is-uploaded">
			<label id="is-uploaded"></label>
		</div>
	</div>
</div>