<div class="diary-entry disable-display">
	<div class="row">
		<div class="col-md-3 left-option">
			<h3 class="left-btn">CF</h3>
		</div>
		<div class="col-md-1 middle-option">
			<input type="checkbox" name="switch" id="switch">
		</div>
		<div class="col-md-3 right-option">
			<h3 class="right-btn">SELF</h3>
		</div>
	</div>
	<div class="row disable-display">
		<p id='diaryEntryApiResponse'></p>
	</div>
</div>